// AUTO-GENERATED by scripts/stamp-faq-cache-key.mjs — do not edit by hand.
// Hash of content/faq/*.md. Imported by app/blog/[slug]/page.tsx so that any
// FAQ content change invalidates the blog pages’ Next.js build cache and the
// "Related questions" spokes regenerate. See claude/blog-spoke-stale-cache-*.md.
export const FAQ_CACHE_KEY = 'a829d795efce68ea'
